services:
  wireguard:
    container_name: gateway_wireguard
    image: linuxserver/wireguard:1.0.20250521-r1-ls116@sha256:f33891344345b1f78705e723b633e3a3f94d08ae75ca1a5f48c5a449c35bf460
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      TZ: ${TZ:?}
      WG_PRIVATE_KEY: ${WG_PRIVATE_KEY:?}
      WG_CADDY_PUBLIC_KEY: ${WG_CADDY_PUBLIC_KEY:?}
      WG_CADDY_PRESHARED_KEY: ${WG_CADDY_PRESHARED_KEY:?}
      WG_FORGEJO_PUBLIC_KEY: ${WG_FORGEJO_PUBLIC_KEY:?}
      WG_FORGEJO_PRESHARED_KEY: ${WG_FORGEJO_PRESHARED_KEY:?}
    volumes:
      - type: bind
        source: ./ifscript.sh
        target: /ifscript.sh/
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./wg0.conf.template
        target: /wg0.conf.template
        read_only: true
        bind:
          create_host_path: false
    entrypoint:
      [
        "bash",
        "-c",
        "apk add --no-cache envsubst && mkdir -p /config/wg_confs && envsubst < /wg0.conf.template > /config/wg_confs/wg0.conf && exec /init",
      ]
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 22:22
      - 51821:51821/udp
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped
