services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    group_add:
      - ${GID_DOCKER:?}
    ports:
      - 82:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_STORAGE_PATH:?}/dockge/data:/app/data
      - ${DOCKGE_STACKS_DIR:?}:${DOCKGE_STACKS_DIR:?}:ro
    environment:
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR:?}
      - DOCKGE_ENABLE_CONSOLE=true
    networks:
      - caddy
networks:
  caddy:
    external: true
