services:
  dockge:
    image: louislam/dockge:1.5.0@sha256:335c6368b880ecc203236ed89e6e5232e0d6578e8ef5920e4a502390451502bf
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    group_add:
      - ${GID_DOCKER:?}
    ports:
      - 82:5001
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/dockge/data
        target: /app/data
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKGE_STACKS_DIR:?}
        target: ${DOCKGE_STACKS_DIR:?}
        read_only: true
        bind:
          create_host_path: false
    environment:
      - TZ=${TZ:?}
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR:?}
      - DOCKGE_ENABLE_CONSOLE=true
    networks:
      - caddy
networks:
  caddy:
    external: true
