services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.7.2@sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b
    user: ${PUID:?}:${PGID:?}
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}

  matterjs-server:
    container_name: homeassistant_matterjs-server
    image: ghcr.io/matter-js/matterjs-server:1.1.7@sha256:e52dc38320b53a0611628a8c3ed416a0dbb47c98ff83c9ef815f4184373f27b5
    read_only: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/matter-server
        target: /data
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}

  otbr:
    container_name: homeassistant_otbr
    # https://github.com/openthread/ot-br-posix/releases/tag/v2026.07.0
    image: openthread/border-router:sha-ec16e39@sha256:611b28c77cdff41279cbb5b29d0a41fcdc5a1ecb402a2b19bde1b8f5f7c6c912
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - ${OT_RCP_DEVICE:?}:/dev/ttyACM0
      - /dev/net/tun:/dev/net/tun
    environment:
      OT_RCP_DEVICE: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
      OT_INFRA_IF: ${OT_INFRA_IF:?}
      OT_THREAD_IF: wpan0
      OT_LOG_LEVEL: 7
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/otbr
        target: /data
        bind:
          create_host_path: false

  mosquitto:
    container_name: homeassistant_mosquitto
    image: eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    user: ${PUID:?}:${PGID:?}
    restart: unless-stopped
    ports:
      - 1883:1883
    environment:
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: ./mosquitto
        target: /mosquitto/config
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/mosquitto/data
        target: /mosquitto/data
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/mosquitto/log
        target: /mosquitto/log
        bind:
          create_host_path: false
