services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.8.2@sha256:56690a89c79a0de98035e1719f8324a92d5859c1192ff45adb0230ea81cb42a5
    user: ${PUID:?}:${PGID:?}
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}

  matterjs-server:
    container_name: homeassistant_matterjs-server
    image: ghcr.io/matter-js/matterjs-server:1.4.0@sha256:54232d0d3e7dff5a54759469d2753399270412b4c30c55b31750a4595e4cb236
    read_only: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/matter-server
        target: /data
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}
      ENABLE_TIME_SYNC: 1

  otbr:
    container_name: homeassistant_otbr
    # https://github.com/openthread/ot-br-posix/releases/tag/v2026.08.0
    image: openthread/border-router:sha-337711e@sha256:c1c047257ae0ed4baa471e4122ba295c3c83b42c34848a3eabe7950e18d3f328
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - ${OT_RCP_DEVICE:?}:/dev/ttyACM0
      - /dev/net/tun:/dev/net/tun
    environment:
      OT_RCP_DEVICE: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
      OT_INFRA_IF: ${OT_INFRA_IF:?}
      OT_THREAD_IF: wpan0
      OT_LOG_LEVEL: 7
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/otbr
        target: /data
        bind:
          create_host_path: false

  mosquitto:
    container_name: homeassistant_mosquitto
    image: eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    user: ${PUID:?}:${PGID:?}
    restart: unless-stopped
    ports:
      - 1883:1883
    environment:
      TZ: ${TZ:?}
    volumes:
      - type: bind
        source: ./mosquitto
        target: /mosquitto/config
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/mosquitto/data
        target: /mosquitto/data
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/homeassistant/mosquitto/log
        target: /mosquitto/log
        bind:
          create_host_path: false
