services:
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:6.1.0@sha256:b6b0890047e833158370d59ed5ef289b3e67a58f4a363cd37ef5c09d170d8543
    restart: unless-stopped
    environment:
      MODE: standalone
    networks:
      - caddy
networks:
  caddy:
    external: true
