services:
  librespeed:
    container_name: librespeed
    image: ghcr.io/librespeed/speedtest:6.2.1@sha256:705744f487048f209b4e389312ea82d4d5c36a76db3e5123b97d4b1649b724b5
    restart: unless-stopped
    environment:
      MODE: standalone
    networks:
      - caddy
networks:
  caddy:
    external: true
