services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/adguardhome/conf
        target: /opt/adguardhome/conf
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/adguardhome/work
        target: /opt/adguardhome/work
        bind:
          create_host_path: false
    ports:
      - ${HOST_IP:?}:53:53/tcp # DNS
      - ${HOST_IP:?}:53:53/udp # DNS
      - 3000:3000/tcp # initial setup
    environment:
      TZ: ${TZ:?}
    networks:
      - caddy
    user: ${PUID:?}:${PGID:?}
networks:
  caddy:
    external: true
