services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/adguardhome/conf
        target: /opt/adguardhome/conf
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/adguardhome/work
        target: /opt/adguardhome/work
        bind:
          create_host_path: false
    ports:
      - ${HOST_IP:?}:53:53/tcp # DNS
      - ${HOST_IP:?}:53:53/udp # DNS
      - 3000:3000/tcp # initial setup
    environment:
      TZ: ${TZ:?}
    networks:
      - caddy
    user: ${PUID:?}:${PGID:?}
networks:
  caddy:
    external: true
