services:
  adguardhome:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes:
      - ${APPDATA_STORAGE_PATH:?}/adguardhome/conf:/opt/adguardhome/conf
      - ${APPDATA_STORAGE_PATH:?}/adguardhome/work:/opt/adguardhome/work
    ports:
      - ${HOST_IP:?}:53:53/tcp
      - ${HOST_IP:?}:53:53/udp
    environment:
      - TZ=${TZ:?}
    networks:
      - caddy
    user: ${PUID:?}:${PGID:?}
networks:
  caddy:
    external: true
