services:
  wireguard:
    container_name: forgejo_wireguard
    image: linuxserver/wireguard:1.0.20260223-r0-ls120@sha256:3abfd4b82212106e357989750b9c0c9859aa511f5305a9a55c18c8de7198b655
    cap_add:
      - NET_ADMIN
    environment:
      PUID: ${PUID:?}
      PGID: ${PGID:?}
      TZ: ${TZ:?}
      DOMAIN: ${DOMAIN:?}
      HOME_NETWORK: ${HOME_NETWORK:?}
      WG_GATEWAY_PUBLIC_KEY: ${WG_GATEWAY_PUBLIC_KEY:?}
      WG_PRIVATE_KEY: ${WG_FORGEJO_PRIVATE_KEY:?}
      WG_PRESHARED_KEY: ${WG_FORGEJO_PRESHARED_KEY:?}
      WG_ADDRESS: 10.0.0.3
    volumes:
      - type: bind
        source: ../../wireguard/ifscript.sh
        target: /ifscript.sh/
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ../../wireguard/wg0.conf.template
        target: /wg0.conf.template
        read_only: true
        bind:
          create_host_path: false
    entrypoint:
      [
        "bash",
        "-c",
        "apk add --no-cache envsubst && mkdir -p /config/wg_confs && envsubst < /wg0.conf.template > /config/wg_confs/wg0.conf && exec /init",
      ]
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    ports:
      - 22:22
    networks:
      - caddy
    dns:
      # set dns to cloudflare so the domain for the wireguard endpoint resolves correctly,
      # even if the domain is rewritten to the local server address locally
      - 1.1.1.1

  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:16.0.0-rootless@sha256:33a27fad6fab44e585e86ab185ba882cbf9fd6ed28b368863474a580c526f75c
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    network_mode: service:wireguard
    volumes:
      - ${APPDATA_STORAGE_PATH:?}/forgejo/data:/var/lib/gitea
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:?}
      - FORGEJO__server__START_SSH_SERVER=true
      - FORGEJO__server__SSH_LISTEN_PORT=22
      - FORGEJO__server__SSH_PORT=22
      - FORGEJO__log__MODE=file
      - FORGEJO__mailer__ENABLED=true
      - FORGEJO__mailer__FROM=forgejo@${DOMAIN:?}
      - FORGEJO__mailer__PROTOCOL=smtps
      - FORGEJO__mailer__SMTP_ADDR=mail-eu.smtp2go.com
      - FORGEJO__mailer__SMTP_PORT=465
      - FORGEJO__mailer__USER=forgejo@${DOMAIN:?}
      - FORGEJO__mailer__PASSWD=${FORGEJO_SMTP_PASSWORD:?}

networks:
  caddy:
    external: true
