services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    user: ${PUID:?}:${PGID:?}
    environment:
      - TZ=${TZ:?}
      - PORT=80
    volumes:
      - ${APPDATA_STORAGE_PATH:?}/jellyseerr/config:/app/config
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true
