services:
  vpn:
    container_name: qbittorrent_vpn
    image: thrnz/docker-wireguard-pia:20260501_master_eb24c58@sha256:8cd0211f5b8043214d572c33bc4e506665f5331db5d86ae6312d41b6dd494e5f
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./update-port-qbt.sh
        target: /update-port-qbt.sh
        read_only: true
        bind:
          create_host_path: false
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ:?}
      LOC: swiss
      LOCAL_NETWORK: 172.16.0.0/12,${HOME_NETWORK:?}
      PORT_FORWARDING: "1"
      PORT_SCRIPT: /update-port-qbt.sh
      EXIT_ON_FATAL: "1"
      USER: ${PIA_USER:?}
      PASS: ${PIA_PASS:?}
    sysctls:
      # The wg-quick script tries to set this when setting up routing, however this requires running the container
      # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
      # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 300s
      timeout: 10s
      start_period: 30s
      start_interval: 3s
    networks:
      - caddy
  qbittorrent:
    container_name: qbittorrent
    image: qbittorrentofficial/qbittorrent-nox:5.2.0-1@sha256:84818ffc8006e9d67486e84042a422f7751c44d79a3e2c2df74a296789c2c2b6
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      QBT_LEGAL_NOTICE: confirm
      QBT_WEBUI_PORT: "80"
    tmpfs:
      - /tmp
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/qbittorrent/qbt-config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media
        target: /mnt/nas-media
        bind:
          create_host_path: false
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media
        target: /mnt/media
        bind:
          create_host_path: false
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy
networks:
  caddy:
    external: true
