services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
    user: ${PUID:?}:${PGID:?}
    group_add:
      - ${GID_VIDEO:?}
      - ${GID_RENDER:?}
      - ${PGID:?}
    volumes:
      - ${APPDATA_STORAGE_PATH:?}/jellyfin/config:/config
      - ${APPDATA_STORAGE_PATH:?}/jellyfin/cache:/cache
      - ${MEDIA_STORAGE_PATH:?}/media:/media
      - type: tmpfs
        target: /config/transcodes
        tmpfs:
          mode: 511
    restart: unless-stopped
    environment:
      - TZ=${TZ:?}
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN:?}
    ports:
      - 7359:7359/udp # client discovery
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    networks:
      - caddy
networks:
  caddy:
    external: true
