services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    user: ${PUID:?}:${PGID:?}
    group_add:
      - ${GID_VIDEO:?}
      - ${GID_RENDER:?}
      - ${PGID:?}
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/jellyfin/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/jellyfin/cache
        target: /cache
        bind:
          create_host_path: false
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media
        target: /media
        bind:
          create_host_path: false
      - type: tmpfs
        target: /config/transcodes
        tmpfs:
          mode: 511
    restart: unless-stopped
    environment:
      TZ: ${TZ:?}
      JELLYFIN_PublishedServerUrl: https://jellyfin.${DOMAIN:?}
    ports:
      - 7359:7359/udp # client discovery
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    networks:
      - caddy
networks:
  caddy:
    external: true
