services:
  wireguard:
    container_name: caddy_wireguard
    image: linuxserver/wireguard:1.0.20250521-r1-ls107@sha256:b199fa09846365caec217ebf9cbf839a22b7bf836acfd367a59ed52b6984f174
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      - TZ=${TZ:?}
      - DOMAIN=${DOMAIN:?}
      - HOME_NETWORK=${HOME_NETWORK:?}
      - WG_PRIVATE_KEY=${WG_PRIVATE_KEY:?}
      - WG_GATEWAY_PUBLIC_KEY=${WG_GATEWAY_PUBLIC_KEY:?}
      - WG_PRESHARED_KEY=${WG_PRESHARED_KEY:?}
    volumes:
      - type: bind
        source: ./wireguard/ifscript.sh
        target: /ifscript.sh/
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./wireguard/wg0.conf.template
        target: /wg0.conf.template
        read_only: true
        bind:
          create_host_path: false
    entrypoint:
      [
        "bash",
        "-c",
        "apk add --no-cache envsubst && mkdir -p /config/wg_confs && envsubst < /wg0.conf.template > /config/wg_confs/wg0.conf && exec /init",
      ]
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - caddy
    dns:
      # set dns to cloudflare so the domain for the wireguard endpoint resolves correctly,
      # even if the domain is rewritten to the local server address locally
      - 1.1.1.1
  caddy:
    container_name: caddy
    image: caddy:2.11.2-alpine@sha256:fce4f15aad23222c0ac78a1220adf63bae7b94355d5ea28eee53910624acedfa
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./caddy/
        target: /etc/caddy/
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/caddy/data
        target: /data
        bind:
          create_host_path: false
    network_mode: service:wireguard
    environment:
      - TZ=${TZ:?}
      - DOMAIN=${DOMAIN:?}
      - OLD_NEXTCLOUD_DOMAIN=${OLD_NEXTCLOUD_DOMAIN:?}
      - HOME_NETWORK=${HOME_NETWORK:?}
      - HOST_IP=${HOST_IP:?}
networks:
  caddy:
    name: caddy
