services:
  wireguard:
    build:
      dockerfile_inline: |
        FROM linuxserver/wireguard:latest
        RUN apk add --no-cache envsubst
      pull: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      - TZ=${TZ:?}
      - DOMAIN=${DOMAIN:?}
      - HOME_NETWORK=${HOME_NETWORK:?}
      - WG_PRIVATE_KEY=${WG_PRIVATE_KEY:?}
      - WG_GATEWAY_PUBLIC_KEY=${WG_GATEWAY_PUBLIC_KEY:?}
      - WG_PRESHARED_KEY=${WG_PRESHARED_KEY:?}
    volumes:
      - ./wireguard/ifscript.sh:/ifscript.sh/:ro
      - ./wireguard/wg0.conf.template:/wg0.conf.template:ro
    entrypoint:
      [
        "bash",
        "-c",
        "mkdir -p /config/wg_confs && envsubst < /wg0.conf.template > /config/wg_confs/wg0.conf && exec /init",
      ]
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - caddy
    dns:
      # set dns to cloudflare so the domain for the wireguard endpoint resolves correctly,
      # even if the domain is rewritten to the local server address locally
      - 1.1.1.1
  caddy:
    image: caddy:latest
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/:/etc/caddy/:ro
      - ${APPDATA_STORAGE_PATH:?}/caddy/data:/data
    network_mode: service:wireguard
    environment:
      - TZ=${TZ:?}
      - DOMAIN=${DOMAIN:?}
      - OLD_NEXTCLOUD_DOMAIN=${OLD_NEXTCLOUD_DOMAIN:?}
      - HOME_NETWORK=${HOME_NETWORK:?}
      - HOST_IP=${HOST_IP:?}
networks:
  caddy:
    name: caddy
