services:
  seerr:
    container_name: seerr
    image: seerr/seerr:v3.4.1@sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      PORT: "80"
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/seerr/config
        target: /app/config
        bind:
          create_host_path: false
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true
