services:
  seerr:
    container_name: seerr
    image: seerr/seerr:v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      PORT: "80"
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/seerr/config
        target: /app/config
        bind:
          create_host_path: false
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true
