services:
  seerr:
    container_name: seerr
    image: seerr/seerr:v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
    user: ${PUID:?}:${PGID:?}
    environment:
      TZ: ${TZ:?}
      PORT: "80"
    volumes:
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/seerr/config
        target: /app/config
        bind:
          create_host_path: false
    restart: unless-stopped
    networks:
      - caddy
networks:
  caddy:
    external: true
