services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf:2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    networks:
      - caddy
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media/Audiobooks
        target: /audiobooks
        bind:
          create_host_path: false
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media/Podcasts
        target: /podcasts
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/audiobookshelf/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/audiobookshelf/metadata
        target: /metadata
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}
networks:
  caddy:
    external: true
