services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    networks:
      - caddy
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media/Audiobooks
        target: /audiobooks
        bind:
          create_host_path: false
      - type: bind
        source: ${MEDIA_STORAGE_PATH:?}/media/Podcasts
        target: /podcasts
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/audiobookshelf/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_STORAGE_PATH:?}/audiobookshelf/metadata
        target: /metadata
        bind:
          create_host_path: false
    environment:
      TZ: ${TZ:?}
networks:
  caddy:
    external: true
