services:
  audiobookshelf:
    image: advplyr/audiobookshelf:2.33.1@sha256:a4a5841bba093d81e5f4ad1eaedb4da3fda6dbb2528c552349da50ad1f7ae708
    restart: unless-stopped
    user: ${PUID:?}:${PGID:?}
    networks:
      - caddy
    volumes:
      - ${MEDIA_STORAGE_PATH:?}/media/Audiobooks:/audiobooks
      - ${MEDIA_STORAGE_PATH:?}/media/Podcasts:/podcasts
      - ${APPDATA_STORAGE_PATH:?}/audiobookshelf/config:/config
      - ${APPDATA_STORAGE_PATH:?}/audiobookshelf/metadata:/metadata
    environment:
      - TZ=${TZ:?}
networks:
  caddy:
    external: true
